version: "3.9"

services:
  postgres:
    # image: postgres:17-alpine
    image: pgvector/pgvector:pg17
    container_name: docmind-postgres

    restart: unless-stopped

    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: docmind_ai

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: